### ISSUE TITLE
Outpost example not returning anything

### ISSUE THREAD

**Issue by elenaran** [ScriptLineStudios/pybiomes#1]
Hey, I'm able to run the first sample just fine, but on the second one, nothing ever comes back. Even if I prefilter the seeds to search down to one that I know has an outpost at 0,0 (113758).

the is_viable_structure_pos() function returns false

**Comment by ScriptLineStudios** [comment]
fixed as per the discussion we had here: https://discord.com/channels/720723932738486323/720723933208379463/1316524804664332309 

thanks for raising this!
